name: server
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  protos:
    path: ../protos

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
